replacement for make
adriencaccia/vscode-flask-debug pull request #1
Opened 2020-07-19 06:30 UTC by orcema

make didn't work on windows 10, thus i setup tasks for reproducing the make instructions.
shortcut in VSCode for displaying all tasks:  `ctrl+alt+t`

2020-07-20 16:25 UTC, adriencaccia requested changes
Thank you very much for this PR :heart: !

Can you also add a `For Windows users` section in the `README.md`, explaining how to execute the tasks ?

2020-07-20 16:25 UTC, adriencaccia commented on .vscode/tasks.json
> +  }
Could you add an empty line at the end of file ?

2020-07-20 16:25 UTC, adriencaccia commented on .vscode/tasks.json
> +{
Could you rename the commit with something more explicit, like `Add VS Code tasks`

2020-07-21 04:28 UTC, orcema commented
i will setup a new pull request

2020-07-21 04:28 UTC, closed without merging